### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by apc** [wo/bdrc#1]
Unless you're using some notation I'm not familiar with, there seems to be a typo [here](https://github.com/wo/bdrc/blob/acc35095a3ba819e3a832152fb40de5c04742c01/05-utility.tex#L621): `Whenever an agent desires $A\land B$, they also desire $AB$.`

Thanks for posting these notes—going over them preparing for a course I'll be teaching and have found them incredibly helpful.

**Comment by wo** [comment]
Thanks! Glad you find the notes useful.
